### ISSUE TITLE
跑起来服务以后，调本地接口返回500  服务器内部错误

### ISSUE THREAD

**Issue by GetlemanSmallHao** [sealtalk/sealtalk-server#10]
Cannot read property 'toString' of undefined

**Comment by yuhongda0315** [comment]
参数是通过 body 体传递的，不是 URL，详细可源码：https://github.com/sealtalk/sealtalk-server/blob/master/src/routes/user.js

![image](https://user-images.githubusercontent.com/13547775/39221090-a1bea3a8-4867-11e8-8832-9436ee906635.png)

**Comment by angeless-jacky** [comment]
> [http：// localhost：8585 / user / check_phone_available？phone = 13912345678＆region = 86](http://localhost:8585/user/check_phone_available?phone=13912345678&region=86) 我在本地调用这个api然后返回的是上述的东西
你要部署 到线上服务器，一个 服务端 ，一个 客户端 ，客户端请求服务端 就可以了 你看他的 文档配置 有说明的

**Comment by FrancisLL** [comment]
check_phone_available  接口传入参数的方式是 body 体，不是 URL。
源码地址：https://github.com/sealtalk/sealtalk-server/blob/master/src/routes/user.js
