### ISSUE TITLE
还有邀请的 url 是多少呢

### ISSUE THREAD

**Issue by tccLaravel** [sealtalk/sealtalk-server#12]
http://api-cn.ronghub.com/friendship/invite.json

or 

http://api-cn.ronghub.com/friendship/invite

但是都访问不了, 404错误  Not a valid API

**Comment by yuhongda0315** [comment]
api-cn.ronghub.com 是融云 Server API 的域名

您访问的 friendship/invite 是 SealTalk Server 的接口，两个 Server 不可混用

把 SealTalk Server 本地服务启动，通过 http://ip+port/friendship/invite 可访问，详细 API 请参考：[https://github.com/sealtalk/sealtalk-server/blob/master/docs/api_friendship.md](https://github.com/sealtalk/sealtalk-server/blob/master/docs/api_friendship.md)
