### ISSUE TITLE
短信发送成功后，后台服务会报错

### ISSUE THREAD

**Issue by 775226853** [sealtalk/sealtalk-server#15]
173323 is not a valid string

173323就是发送出来的验证码

**Comment by gr4yk3r** [comment]
> 173323 is not a valid string
> 
> 173323就是发送出来的验证码

我也碰到这个问题了，后来发现代码有一个bug，util/sms.js里有一行 result.sessionId = code;  改成 result.sessionId = `${code}`;就行了，code是数值类型，数据库那边定义的是字符串，所以报 is not a valid string。
