### ISSUE TITLE
无法获取聊天的历史记录

### ISSUE THREAD

**Issue by jinrenjie** [sealtalk/sealtalk-server#17]
<img width="467" alt="屏幕快照 2019-11-13 下午10 47 06" src="https://user-images.githubusercontent.com/5665135/68774525-32fc9180-0668-11ea-9814-1fa5807da050.png">

**Comment by FrancisLL** [comment]
获取历史消息需要在融云开发者后台开通 单群聊消息云端存储服务，开通位置： 开发者后台 -> 服务管理 -> IM 服务 -> IM 商用版 -> 单群聊消息云端存储
