### ISSUE TITLE
该开源项目的用户数量是否有限制

### ISSUE THREAD

**Issue by Yecgaa1** [sealtalk/sealtalk-server#18]
是否遵循官网上的那种价格制度
还是没有限制？
谢谢

**Comment by arielyang** [comment]
这个开源项目也要调用融云的服务的。这个项目是 App Server，IM 服务要使用融云的公有云服务。

**Comment by Yecgaa1** [comment]
那么用户人数是有限制对吗？
还有就是一定需要七牛云吗？

**Comment by YongHao0** [comment]
1. App Server 本身没有限制. 融云服务的人数限制以及对应价格您可咨询官方说明
[http://www.rongcloud.cn/](http://www.rongcloud.cn/)
2. SealTalk 默认使用七牛云上传. 但 SealTalk 为开源项目, 开发者可修改上传逻辑. 也就是说: 不一定必须使用七牛云, 可根据开发者业务做修改
