### ISSUE TITLE
npm run initdb error

### ISSUE THREAD

**Issue by liub950511** [sealtalk/sealtalk-server#3]
during execute command "npm run initdb", the error message is: SyntaxError: in D:\sealtalk-server-master\src\db.coffee, reserved word "yield" on line 89

**Comment by arielyang** [comment]
what's your node version?

**Comment by liaobaocheng** [comment]
- I got the same error.i simply translate the `db.coffee` to `db.js` using [js to coffee](http://js2.coffee/) 
- Also,translate `util.coffee` to `util.js`,and then it work!.
- 将db.coffee和util.coffee用http://js2.coffee/转成javascript格式就好了。
