### ISSUE TITLE
src/db.coffee, reserved word "yield" on line 100

### ISSUE THREAD

**Issue by woshibushibu** [sealtalk/sealtalk-server#5]
When I run "npm run initdb".
It shows:
> coffee --nodejs --harmony sync.coffee

(node:14971) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
SyntaxError: In /home/build/sealtalk-server/src/db.coffee, reserved word "yield" on line 100

What should I do?????

**Comment by woshibushibu** [comment]
97 groupMemberClassMethods =
 98   bulkUpsert: (groupId, memberIds, timestamp, transaction, creatorId) ->
 99     co ->
100       groupMembers = yield GroupMember.unscoped().findAll
101         where:
102           groupId: groupId
103         attributes: [
104           'memberId'
105           'isDeleted'
106         ]
107

**Comment by yuhongda0315** [comment]
what's your coffee version?
please try reinstall the coffee.
