### ISSUE TITLE
android端发送验证手机是否注册和进行登录出现json解析异常

### ISSUE THREAD

**Issue by bozaixing** [sealtalk/sealtalk-server#6]
异常信息为：
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**Comment by arielyang** [comment]
请问错误的 JSON 数据是什么？

**Comment by FrancisLL** [comment]
开发者您好，
请问当前是否还有问题？
若有问题，请您详细描述下错误的 JSON 数据是什么？
若无问题，将在一天后关闭 issue

**Comment by FrancisLL** [comment]
开发者未回复，关闭 issue
