### ISSUE TITLE
收不到短信

### ISSUE THREAD

**Issue by lifeofwind** [sealtalk/sealtalk-server#8]
按步骤来安装的，key什么的都没问题
请求也显示了：json:{"code":200} 631.1ms
但是就是收不到短信。

**Comment by microfar** [comment]
我也遇到统一问题。配置了conf.js  也不好用。

**Comment by shuise** [comment]
1：需要开通短信服务并配置
2：请参考具体代码实现，development 下是开发测试，并不会请求短信，是为了节省费用，需要调用请做对应调整

**Comment by lifeofwind** [comment]
@microfar  开发模式是：提供测试的环境，许多地方不会真正调用。
生产模式是：许多接口之类的都正式接入，正式使用。
这个两个模式，和后台的开发模式和生产模式没有什么联系，server用生产模式，那是server的事，语音描述上可能不好理解，直接把server改成生产模式运行，就OK了，融云后台继续开发模式，也是可以的，不必统一，也不必去改sealtalk-server的开发模式代码。

**Comment by FrancisLL** [comment]
V2.1.0 版本短信服务使用的是 第三方 云片，您需注册配置云片相关信息后，再配置 conf.js 文件中配置，方可使用。
