### ISSUE TITLE
pm2部署问题

### ISSUE THREAD

**Issue by onep2p** [sealtalk/sealtalk-server#9]
目前卡在pm2的部署上
![image](https://user-images.githubusercontent.com/12823542/35080816-f2b684ec-fc4a-11e7-86c1-dc242e022021.png)

我用pm2 start 启动后status是错误的   这个怎么解决呢？

**Comment by YongHao0** [comment]
sealtalk-server 配置正确后, 建议您
1. 首先生成部署文件, 命令:
```js
grunt release
```
2. 配置环境为生产环境:
```js
Windows : set NODE_ENV=production
Mac/Linux : export NODE_ENV=production
```
3. 进入 dist 目录, 使用 pm2 启动 index.js 文件
